### ISSUE TITLE
AceAddon appears to be out of date

### ISSUE THREAD

**Issue by KevinTyrrell** [Anonomit/ZeraTooltip#2] opened 2022-09-10 04:32 UTC
Stacktrace
```
152x AceLocale-3.0-6: ZeraTooltip: Missing entry for 'Block Rating'
[string "@ZeraTooltip\Config.lua"]:662: in function `MakeColorsOptionsTable'
[string "@ZeraTooltip\ZeraTooltip-1.5.1.lua"]:445: in function `CreateOptions'
[string "@ZeraTooltip\ZeraTooltip-1.5.1.lua"]:480: in function <ZeraTooltip\ZeraTooltip.lua:473>
[string "=[C]"]: ?
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...ceDetails\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...ceDetails\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>
```

Strange that it picks out block rating, as I believe nothing has changed with that stat in particular.

**Comment by Anonomit** [comment] 2022-09-22 02:47
This issue was caused by a strict version check that was only looking for TBC or Classic. Since Wrath is not TBC, it didn't load some entries that it should have. This is fixed with the Wrath rewrite in v2.0.0 (d10a54e497fc0ad2ac034a1a6fee7c8ce1007d69).

**Closed as completed by Anonomit** 2022-09-22 02:47 UTC
